// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Athlete struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}
