// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/Stratoscale/swagger/query"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/zone-six/microservice-template/internal/clients/rest/restapi/operations"
	"github.com/zone-six/microservice-template/internal/clients/rest/restapi/operations/todos"

	models "github.com/zone-six/microservice-template/internal/clients/rest/models"
)

type contextKey string

const AuthKey contextKey = "Auth"

//go:generate mockery -name TodosAPI -inpkg

// TodosAPI
type TodosAPI interface {
	Get(ctx context.Context, params todos.GetParams) middleware.Responder
	AddOne(ctx context.Context, params todos.AddOneParams) middleware.Responder
	DestroyOne(ctx context.Context, params todos.DestroyOneParams) middleware.Responder
	UpdateOne(ctx context.Context, params todos.UpdateOneParams) middleware.Responder
}

// Config is configuration for Handler
type Config struct {
	TodosAPI
	Logger func(string, ...interface{})
	// InnerMiddleware is for the handler executors. These do not apply to the swagger.json document.
	// The middleware executes after routing but before authentication, binding and validation
	InnerMiddleware func(http.Handler) http.Handler

	// Authorizer is used to authorize a request after the Auth function was called using the "Auth*" functions
	// and the principal was stored in the context in the "AuthKey" context value.
	Authorizer func(*http.Request) error
}

// Handler returns an http.Handler given the handler configuration
// It mounts all the business logic implementers in the right routing.
func Handler(c Config) (http.Handler, error) {
	spec, err := loads.Analyzed(swaggerCopy(SwaggerJSON), "")
	if err != nil {
		return nil, fmt.Errorf("analyze swagger: %v", err)
	}
	api := operations.NewTodoListAPI(spec)
	api.ServeError = errors.ServeError
	api.Logger = c.Logger

	api.JSONConsumer = runtime.JSONConsumer()
	api.JSONProducer = runtime.JSONProducer()
	api.TodosGetHandler = todos.GetHandlerFunc(func(params todos.GetParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.TodosAPI.Get(ctx, params)
	})
	api.TodosAddOneHandler = todos.AddOneHandlerFunc(func(params todos.AddOneParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.TodosAPI.AddOne(ctx, params)
	})
	api.TodosDestroyOneHandler = todos.DestroyOneHandlerFunc(func(params todos.DestroyOneParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.TodosAPI.DestroyOne(ctx, params)
	})
	api.TodosUpdateOneHandler = todos.UpdateOneHandlerFunc(func(params todos.UpdateOneParams) middleware.Responder {
		ctx := params.HTTPRequest.Context()
		return c.TodosAPI.UpdateOne(ctx, params)
	})
	api.ServerShutdown = func() {}
	return api.Serve(c.InnerMiddleware), nil
}

// Query parse functions for all the models
// Those can be used to extract database query from the http path's query string
var (
	ErrorQueryParse = query.MustNewBuilder(&query.Config{Model: models.Error{}}).ParseRequest
	ItemQueryParse  = query.MustNewBuilder(&query.Config{Model: models.Item{}}).ParseRequest
)

// swaggerCopy copies the swagger json to prevent data races in runtime
func swaggerCopy(orig json.RawMessage) json.RawMessage {
	c := make(json.RawMessage, len(orig))
	copy(c, orig)
	return c
}

// authorizer is a helper function to implement the runtime.Authorizer interface.
type authorizer func(*http.Request) error

func (a authorizer) Authorize(req *http.Request, principal interface{}) error {
	if a == nil {
		return nil
	}
	ctx := storeAuth(req.Context(), principal)
	return a(req.WithContext(ctx))
}

func storeAuth(ctx context.Context, principal interface{}) context.Context {
	return context.WithValue(ctx, AuthKey, principal)
}
